### ISSUE TITLE
The call to polyscope::show() in main.cpp in the vector field decomposition project causes it to abort

### ISSUE THREAD

**Issue by Fletterio** [GeometryCollective/ddg-exercises#11]
Hello, I'm currently trying to implement the sixth assignment in the course. However when trying to run the project, after calling polyscope::show() on line 463 the program crashes and says abort() has been called

Here's the callstack and the assert causing the abort: 
![image](https://github.com/GeometryCollective/ddg-exercises/assets/40742817/2929ce2e-21bc-42ef-b653-5953d4a81023)

**Comment by nzfeng** [comment]
I'm not able to reproduce your error, and I'm not really sure what the cause could be. I wasn't able to find your issue among [the existing issues on the official Polyscope repo](https://github.com/nmwsharp) (Maybe you can take a look there yourself if you have a hunch of what related issues might be.) Are you able to build and run the other projects without this error?

Just to make sure, you are using the version of Polyscope linked in this repo via submodule and not using, for example, your own fork of Polyscope?

In the past, I've experienced GLFW errors after updating my system software (after which I need to restart my computer), but this doesn't seem related to me.

**Comment by Fletterio** [comment]
I cloned the repo from scratch, built the vector decomposition project and tried compiling and running it, and the error is the same

The other projects in my fork run just fine, it's this one in particular that I seem to be having trouble running

If you can't reproduce it then it could just be something about my PC or MSVC being weird. I'll try building and running it from another computer with Linux when I get the chance to see if I can get it to work. Thanks!

**Comment by nzfeng** [comment]
Oh yes, I forgot to mention I use Linux and Mac, so any issues I'm unfamiliar with tend to be Windows-related :). I'm really puzzled why it is this piece of code in particular giving MSVC a hard time.

**Comment by Fletterio** [comment]
I managed to make it run on Linux. Seems to be a problem with Polyscope and MSVC. I'll report it on their repo and close this issue
